### PR TITLE
Pass telephone number parameter to PayPal

### PR DESCRIPTION
**Pull request by rozzilla**
With this commit, when you pay with the "Pay with card option", the phone information is added to the PayPal pop-up.

immagine

### CODE REVIEW

**Comment by dimasch** [comment]
@rozzilla Cool feature!
Let's do it optionally, disabled by default:

```
"paypal": {
  "payWithCardOption": true
  ...
}
```

**Comment by rbianchi-ittweb** [comment]
> @rozzilla Cool feature!
> Let's do it optionally, disabled by default:
> 
> ```
> "paypal": {
>   "payWithCardOption": true
>   ...
> }
> ```

This option is enabled by default by PayPal. You can check it right now, also with the current module, clicking here:
image

**Comment by rbianchi-ittweb** [comment]
What I say is that, right now, the phone number is not passed to PayPal. That's the reason for this commit.

**Comment by dimasch** [comment]
Снимок экрана 2020-11-07 в 00 19 44
@rozzilla Thanks, released tag `v1.1.5`

**Comment by rozzilla** [comment]
Great!

**Pull request merged**
