### PR TITLE
Update version to 1.1.3

### PR DESCRIPTION
**Pull request by rozzilla**

### CODE REVIEW

**Comment by rozzilla** [comment]
This commit corrects the calculation of the total taxes and product taxes if VSF is configured with sourcePriceIncludesTax on local.json

**Comment by dimasch** [comment]
@rozzilla  Nice!
Related issue #144 ?

**Comment by rozzilla** [comment]
> @rozzilla Nice!
> Related issue #144 ?

Mmm, I don't think so. We're debugging on it since we have a similar issue. Sometimes the total amount sended to PayPal is different from the sum of the single items... I think that a possible solution is to calculate dynamically the sum, instead of get this data alone...

**Comment by rozzilla** [comment]
> 
> 
> @rozzilla Nice!
> Related issue #144 ?

After a deep analysis and debug I've found that the issue of the wrong prices was related to two things:

- I used an old version of the module, that didn't use the `product.totals` variable
- I didn't get the price included tax, when I've got this option to enable on VSF

So, I can confirm that this commit, that includes the `product.totals` variable and the price with tax, close the issue #144

**Pull request merged**
